import React from 'react'

/**
 * Create a global context
 */
export default React.createContext({
  isLoggedIn: false,
  handleLogin: () => {},
  handleLogout: () => {},
  user: {},
  handleUser: data => {},
  orgs: {},
  currentOrg: {},
  handleOrgs: data => [],
  handleCurrentOrg: value => {},
  loggingIn: false,
  handleLoggingIn: bool => {},
  loadingRepos: true,
  handleLoadingRepos: bool => {},
  currentView: '',
  handleCurrentView: value => {},
  VIEWS: {},
  saveUserSettings: () => {},
  successfulSave: false,
  couldNotSave: false,
  handleHooks: () => {},
  initialHooks: [],
  handleInitialHooks: () => {},
  savingSettingsLoading: false,
  handleSavingSettingsLoading: bool => {},
  fadeOutSaved: false,
  handleFadeOutSaved: bool => {},
  onEvent: {},
  handleOnEvent: data => {},
  newEvent: false,
  handleNewEvent: value => {},
  repos: [],
  handleRepos: data => {},
  activeRepo: '',
  handleActiveRepo: value => {},
  savedNotifications: [],
  handleSavedNotifications: data => {},
  savingSettingsLoadingEmail: false,
  successfulSaveEmail: false,
  couldNotSaveEmail: false,
  handleSavingSettingsLoadingEmail: bool => {},
  handleSuccessfulSaveEmail: bool => {},
  handleCouldNotSaveEmail: bool => {}
})
